name: pynlp
dependencies:
    - python=3.6.3
    - notebook=5.2.1
    - numpy=1.13.3
    - scikit-learn=0.19.1
    - bokeh=0.12.10
    - pip
    - pip:
        - gensim==3.1.0
        - ipython==6.2.1
        - pyLDAvis==2.1.1
        - spacy==2.0.3
